#!/usr/bin/env python
"""
This is an example python script.

Note that its first line that starts #! is a special comment line, 
known as a shebang https://en.wikipedia.org/wiki/Shebang_(Unix)
that tells a Unix-like Operating System that this file is a script 
and that it should run using the python command available in
the environment.

Note to be run the script file also needs 'execute  permission'
"""
import sys

def main(argv):
   """ 
   main function run by the script.
   argv is a list of command line arguments normally got from sys.argv
   """
   print('main function')
   print('argv: ', argv)
   if len(argv) > 0:
       print('name of script argv[0]: ', argv[0])
   if len(argv) == 1:
       print('no command line arguments given')
   else:
       print(len(argv)-1, 'command line arguments given')
       print('list of command line arguments: ', argv[1:])
       print('first command line argument: ', argv[1])

main(sys.argv)
